Finger: [0.040, 0.040,]  # length/m of finger_1, finger_2
InitialPose: { x: 0.0, y: 0.0, z: 0.054641 , theta1: rad(pi/3), theta2: rad(pi/6), }
weight: [1, 1,]
g: 9.8
k: 10000   # N/m
Surface: 2  # 1 || 2 || 3 || 4
Line: {A: -1, B: 10, C: 0}  # B>0!!!
SurfaceLength: 2.00
# 1: plain surface; 2: slant surface; 3: circle
# tau: 10000000  # Pa
# E: 10000000000  # Pa
# beta_ve: 0.2
mu: 0.2

PoseUpdFrequency: 1000   # Hz, make sure >= 1000
ForceFdbFrequency: 100   # Hz
delta_t: 0.005  # s

TailVel: 0.005

## For haptic explore
F_threshold: 0.01

## For contact tooling
ForceCtrlK: 0.5

## For Impedance Controller
ControllerM: 10
ControllerB: 2000
ControllerK: 20